{{- range $index, $microphone := .Values.microphones }}
apiVersion: akri.sh/v0
kind: Configuration
metadata:
  name: {{ template "birdnet-go.fullname" $ }}-mic-{{ $microphone.name }}
  labels:
    app.kubernetes.io/name: {{ template "birdnet-go.name" $ }}
    helm.sh/chart: {{ template "birdnet-go.chart" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/component: rtsp-client
spec:
  capacity: 1
  discoveryHandler:
    discoveryDetails: |
      {{- if $microphone.udevRules }}
      groupRecursive: true
      udevRules:
        {{- range $microphone.udevRules }}
        - {{ . }}
        {{- end }}
      {{- end }}
    name: udev
---
{{- end }}
