# Default values for birdnet-go.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- The number of replicas
replicaCount: 1

akri:
  # -- If true, install Akri
  install: false

birdnet:
  image: ghcr.io/tphakala/birdnet-go:0.5.5
  config: {}

  service:
    type: ClusterIP
    port: 80

  persistentVolumeClaim:
    # -- set to true to use pvc
    enabled: false

    # -- specify an existing `PersistentVolumeClaim` to use
    # existingClaim: ""

    # -- Annotations for the `PersitentVolumeClaim`
    annotations: {}

    accessModes:
      - ReadWriteOnce

    # -- volume claim size
    size: "500Mi"

  ingress:
    enabled: false
    className: ""
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

microphones:
  - name: blueyeti
    udevRules: 
      - ATTRS{idProduct}=="9e84", ATTRS{idVendor}=="b58e"

rtsp:
  client:
    image: lscr.io/linuxserver/ffmpeg:6.1.1
    tolerations: []
  server:
    image: bluenviron/mediamtx:1.8.5

timezone: Europe/Stockholm
