apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "birdnet-go.fullname" . }}-birdnet-go
  labels:
    app.kubernetes.io/name: {{ template "birdnet-go.name" . }}
    helm.sh/chart: {{ template "birdnet-go.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: birdnet-go
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "birdnet-go.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: birdnet-go
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "birdnet-go.name" . }}
        helm.sh/chart: {{ template "birdnet-go.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/component: birdnet-go
    spec:
      containers:
      - image: {{ .Values.birdnet.image }}
        name: birdnet-go
        volumeMounts:
        - mountPath: /config/config.yaml
          name: config
          subPath: config.yaml
        - mountPath: /data
          name: data
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        env:
        - name: TZ
          value: {{ .Values.timezone }}
        resources:
        args:
        - realtime
        {{- range $index, $microphone := .Values.microphones }}
        - --rtsp
        - rtsp://{{ template "birdnet-go.fullname" $ }}-rtsp-server.{{ $.Release.Namespace }}.svc.cluster.local:8554/{{ $microphone.name }}
        {{- end }}
        - --rtsptransport
        - tcp
        livenessProbe:
          tcpSocket:
            port: http
        readinessProbe:
          tcpSocket:
            port: http
      volumes:
      - name: data
        {{- if .Values.birdnet.persistentVolumeClaim.enabled }}
        persistentVolumeClaim:
          claimName: {{ if .Values.birdnet.persistentVolumeClaim.existingClaim }}{{ .Values.birdnet.persistentVolumeClaim.existingClaim }}{{- else }}{{ template "birdnet-go.fullname" . }}{{- end }}
        {{- else }}
        emptyDir: {}
        {{- end }}
      - name: config
        configMap:
          name: {{ template "birdnet-go.fullname" . }}-birdnet-go
