{{- range $index, $microphone := .Values.microphones }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "birdnet-go.fullname" $ }}-rtsp-client-{{ $microphone.name }}
  labels:
    app.kubernetes.io/name: {{ template "birdnet-go.name" $ }}
    helm.sh/chart: {{ template "birdnet-go.chart" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/component: rtsp-client
spec:
  replicas: {{ $.Values.replicaCount }}
  strategy:
    type: Recreate # Needed for akri since bound to single USB device
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "birdnet-go.name" $ }}
      app.kubernetes.io/instance: {{ $.Release.Name }}
      app.kubernetes.io/component: rtsp-client
      microphone: {{ $microphone.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "birdnet-go.name" $ }}
        helm.sh/chart: {{ template "birdnet-go.chart" $ }}
        app.kubernetes.io/instance: {{ $.Release.Name }}
        app.kubernetes.io/managed-by: {{ $.Release.Service }}
        app.kubernetes.io/component: rtsp-client
        microphone: {{ $microphone.name }}
    spec:
      containers:
      - image: lscr.io/linuxserver/ffmpeg:6.1.1
        name: ffmpeg
        args:
        - -nostdin
        - -f
        - alsa
        - -acodec
        - pcm_s16le
        - -ac
        - "2"
        - -ar
        - "48000"
        - -i
        - plughw:1
        - -filter:a
        - "highpass=f=500,dynaudnorm"
        - -f
        - "rtsp"
        - -acodec
        - pcm_s16be
        - rtsp://{{ template "birdnet-go.fullname" $ }}-rtsp-server.{{ $.Release.Namespace }}.svc.cluster.local:8554/{{ $microphone.name }}
        - -rtsp_transport
        - tcp
        env:
        - name: ALSA_CARD
          value: '1'
        resources:
          limits:
            akri.sh/{{ template "birdnet-go.fullname" $ }}-mic-{{ $microphone.name }}: "1"
          requests:
            akri.sh/{{ template "birdnet-go.fullname" $ }}-mic-{{ $microphone.name }}: "1"
      tolerations:
      {{- range $key, $value := $.Values.rtsp.client.tolerations }}
      - {{ toYaml $value | indent 8 }}
      {{- end }}
---
{{- end }}

