apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "birdnet-go.fullname" . }}-rtsp-server
  labels:
    app.kubernetes.io/name: {{ template "birdnet-go.name" . }}
    helm.sh/chart: {{ template "birdnet-go.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: rtsp-server
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "birdnet-go.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: rtsp-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "birdnet-go.name" . }}
        helm.sh/chart: {{ template "birdnet-go.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/component: rtsp-server
    spec:
      containers:
      - image: {{ .Values.rtsp.server.image }}
        name: mediamtx
        env:
        - name: MTX_PROTOCOLS
          value: tcp
        ports:
          - name: rtsp
            containerPort: 8554
            protocol: TCP
