{{- if .Values.birdnet.ingress.enabled -}}
{{- $ingressPath := .Values.birdnet.ingress.path -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "birdnet-go.fullname" . }}-birdnet
  labels:
    app: {{ template "birdnet-go.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- with .Values.birdnet.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.birdnet.ingress.ingressClassName }}
  ingressClassName: {{ .Values.birdnet.ingress.ingressClassName }}
{{- end }}
{{- if .Values.birdnet.ingress.tls }}
  tls:
{{ toYaml .Values.birdnet.ingress.tls | indent 4 }}
{{- end }}
  rules:
  {{- range .Values.birdnet.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: {{ $ingressPath }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ template "birdnet-go.name" . }}
                port: 
                  name: http
  {{- end }}
{{- end }}