{{- if .Values.birdnet.ingress.enabled -}}
{{- $ingressPath := .Values.birdnet.ingress.path -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "birdnet-go.fullname" . }}-birdnet
  labels:
    app.kubernetes.io/name: {{ template "birdnet-go.name" . }}
    helm.sh/chart: {{ template "birdnet-go.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: birdnet-go
  {{- with .Values.birdnet.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.birdnet.ingress.ingressClassName }}
  ingressClassName: {{ .Values.birdnet.ingress.ingressClassName }}
{{- end }}
{{- if .Values.birdnet.ingress.tls }}
  tls:
{{ toYaml .Values.birdnet.ingress.tls | indent 4 }}
{{- end }}
  rules:
  {{- range .Values.birdnet.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: {{ $ingressPath }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ template "birdnet-go.name" . }}-birdnet-go
                port: 
                  name: http
  {{- end }}
{{- end }}