apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "birdnet-go.fullname" . }}-birdnet-go
  labels:
    app.kubernetes.io/name: {{ template "birdnet-go.name" . }}
    helm.sh/chart: {{ template "birdnet-go.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: birdnet-go
data:
  config.yaml: |
  {{- range .Values.birdnet.config }}
    {{ . }}
  {{- end }}
