apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "birdnet-go.fullname" . }}-config
  labels:
    app: {{ template "birdnet-go.name" . }}
    chart: {{ template "birdnet-go.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  config.yaml: |
  {{- range .Values.birdnet.config }}
    {{ . }}
  {{- end }}
