apiVersion: v1
kind: Service
metadata:
  name: {{ template "birdnet-go.fullname" . }}-rtsp-server
  labels:
    app: {{ template "birdnet-go.name" . }}
    chart: {{ template "birdnet-go.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  selector:
    app: {{ template "birdnet-go.name" . }}
  ports:
    - name: rtsp
      protocol: TCP
      port: 8554
      targetPort: rtsp
