apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "birdnet-go.fullname" . }}-rtsp-server
  labels:
    app: {{ template "birdnet-go.name" . }}
    chart: {{ template "birdnet-go.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "birdnet-go.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "birdnet-go.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: {{ .Values.rtsp-server.image }}
        name: mediamtx
        env:
        - name: MTX_PROTOCOLS
          value: tcp
        ports:
          - name: rtsp
            containerPort: 8554
            protocol: TCP
