apiVersion: v1
kind: Service
metadata:
  name: {{ template "birdnet-go.fullname" . }}-birdnet
  labels:
    app: {{ template "birdnet-go.name" . }}
    chart: {{ template "birdnet-go.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  selector:
    app: {{ template "birdnet-go.name" . }}-birdnet
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
