apiVersion: v1
kind: Service
metadata:
  name: {{ template "birdnet-go.fullname" . }}-rtsp-server
  labels:
    app.kubernetes.io/name: {{ template "birdnet-go.name" . }}
    helm.sh/chart: {{ template "birdnet-go.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: rtsp-server
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ template "birdnet-go.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: rtsp-server
  ports:
    - name: rtsp
      protocol: TCP
      port: 8554
      targetPort: rtsp
